DartuContestHosted/src/DartuContestHosted/Controllers/AdminController.cs
using DartuContestHosted.Models;
using DartuContestHosted.Services;
using DartuContestHosted.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace DartuContestHosted.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IParticipantResultsRepository _participantResultsRepository;

        public AdminController(IParticipantResultsRepository participantResultsRepository)
        {
            _participantResultsRepository = participantResultsRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RezultateElevi(int id)
        {
            var results = _participantResultsRepository.GetResults().Where(part => part.Clasa == id).ToList();
            return View(results);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _participantResultsRepository.GetResults().Where(part => part.Id == id).FirstOrDefault();
            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ElevViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newElev = new Rezultate
                {
                    Nume = model.Nume,
                    Clasa = model.Clasa,
                    Prenume = model.Prenume,
                    Scoala = model.Scoala,
                    P1 = model.P1,
                    P2 = model.P2,
                    P3 = model.P3
                };

                _participantResultsRepository.Add(newElev);
                _participantResultsRepository.Commit();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = _participantResultsRepository.Get(id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            _participantResultsRepository.Delete(model);
            _participantResultsRepository.Commit();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, ElevViewModel model)
        {
            var stud = _participantResultsRepository.Get(id);
            if (ModelState.IsValid)
            {
                if(!string.IsNullOrEmpty(model.Nume))
                {
                    stud.Nume = model.Nume;
                }

                if(!string.IsNullOrEmpty(model.Prenume))
                {
                    stud.Prenume = model.Prenume;
                }

                if(!string.IsNullOrEmpty(model.Scoala))
                {
                    stud.Scoala = model.Scoala;
                }

                stud.P1 = model.P1;
                stud.P2 = model.P2;
                stud.P3 = model.P3;
                
                //iterate over the property and see which can be updated
                //Type type = model.GetType();
                //var propertyInfo = type.GetProperties();

                //foreach (var item in propertyInfo)
                //{
                //    var value = item.GetValue(model, null);
                //    if (value != null)
                //    {
                //        //we can make update
                //        item.SetValue(stud, Convert.ChangeType(value, item.PropertyType), null);
                //    }
                //}

                _participantResultsRepository.Commit(); //update
                //update
                return RedirectToAction("Index");
            }
            return View(stud);
        }

    }
}

DartuContestHosted/src/DartuContestHosted/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DartuContestHosted.Models;
using DartuContestHosted.Services;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace DartuContestHosted.Controllers
{
    [Authorize]
    public class ResultController : Controller
    {
        private IParticipantResultsRepository _participantResultsRepository;
        public ResultController(IParticipantResultsRepository participantResultsRepository)
        {
            _participantResultsRepository = participantResultsRepository;
        }
        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RezultateElevi(int id)
        {
            var results = _participantResultsRepository.GetResults().Where(part => part.Clasa == id).ToList();
            return View(results);
        }
    }
}

DartuContestHosted/src/DartuContestHosted/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Stefan Dartu, editia 2017</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <nav class="navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>
                <a asp-area="" asp-controller="Result" asp-action="Index" class="navbar-brand">Rezultate</a>
                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-area="" asp-controller="Admin" asp-action="Index" class="navbar-brand">Admin Operation</a>
                }
            </div>
            <div class="navbar navbar-nav navbar-right">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <hr />
        <br />
        <br />
        <footer>
            <p>@DateTime.Now</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>